{% set version = "3.3.5" %}

package:
    name: fftw
    version: {{ version }}

source:
    fn: fftw-{{ version }}.tar.gz
    url: http://www.fftw.org/fftw-{{ version }}.tar.gz
    sha256: 8ecfe1b04732ec3f5b7d279fdb8efcad536d555f9d1e8fabd027037d45ea8bcf

build:
    skip: True  # [win]
    number: 0

requirements:
    build:
        - perl

test:
    commands:
        - exit $(test -f ${PREFIX}/lib/libfftw3f.a)          # [not win]
        - exit $(test -f ${PREFIX}/lib/libfftw3.a)           # [not win]
        - exit $(test -f ${PREFIX}/lib/libfftw3l.a)          # [not win]
        - exit $(test -f ${PREFIX}/lib/libfftw3f_threads.a)  # [not win]
        - exit $(test -f ${PREFIX}/lib/libfftw3_threads.a)   # [not win]
        - exit $(test -f ${PREFIX}/lib/libfftw3l_threads.a)  # [not win]

about:
    home: http://fftw.org
    license: GPL 2
    summary: "The fastest Fourier transform in the west."


extra:
    recipe-maintainers:
        - alexbw
        - jakirkham
        - jjhelmus
        - grlee77
