package:
  name: openblas
  version: 0.2.14

source:
  fn: openblas-0.2.14.tgz
  url: http://github.com/xianyi/OpenBLAS/tarball/v0.2.14
  md5: d340dc3d8a03f549ae29488d737b9c30

build:
  number: {{CONDA_BUILD_NUMBER}}

  track_features:
    - openblas

requirements:
  build:
    - gcc ==4.8.5

  run:
    - libgcc ==4.8.5

about:
  home: http://xianyi.github.io/OpenBLAS/
  license: BSD
